name: maps_markers
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  location: ^7.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/map_style/
    - assets/icons/
